### ISSUE TITLE
How to hide Static Sites from URL

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#170]
I have the following structure:

-- Level1: Page "products" with ProductManager Plugin "list view" 
Product Page: "category" 
= List of all Categories

--- Level2: Page "category" with ProductManager Plugin "list view"
Product Page "detail"
= List of al Products of this category

---- Level3: Page "detail" with ProductManager Plugin "single view"
Product Page "same"
= Product Detail

With using the RoutingExample i get URLs like
for Level2: mydomain.de/products/category/{category_title_0}
for Level3: mydomain.de/products/category/detail/{category_title_0}/{product_title}

what i want:
for Level2: mydomain.de/products/{category_title_0}
for Level3: mydomain.de/products/{category_title_0}/{product_title}

if i add `../` to the routePath i get an 500-Error
what i tried:
```
# One level categories
      -
        routePath: '../{category_title_0}'
        _controller: 'Product::list'
        _arguments:
          category_title_0: 'category_0'
      -
        routePath: '../../{category_title_0}/{product_title}'
        _controller: 'Product::show'
        _arguments:
          category_title_0: 'category_0'
          product_title: 'product'
```

How can i achieve the url without the static pages of level2/3 in the url?

Thank you for your help
