### ISSUE TITLE
PageTypeSuffix with working wishList pageType & lazyLoading pageType

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#199]
Hello,

i was trying to Map PageType 1533906435 to sitemap.xml but then the Ajax calls (Lazy Loading List etc.) does not work anymore

My Configration:
```
routeEnhancers:
	PageTypeSuffix:
	    type: PageType
	    default: /
	    index: index
	    map:
	      /: 0
	      sitemap.xml: 1533906435
```

does anybody have a working configuration for me?

Thank you very much

**Comment by pixelmatseriks** [comment]
Can you try add it like:
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
```
